package com.geezer.adminapp.hibernate;

// Generated Jul 9, 2013 3:22:56 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Assemble generated by hbm2java
 */
public class Assemble implements java.io.Serializable {

	private Integer assembleNo;
	private Computer computer;
	private Date assembleDate;

	public Assemble() {
	}

	public Assemble(Computer computer, Date assembleDate) {
		this.computer = computer;
		this.assembleDate = assembleDate;
	}

	public Integer getAssembleNo() {
		return this.assembleNo;
	}

	public void setAssembleNo(Integer assembleNo) {
		this.assembleNo = assembleNo;
	}

	public Computer getComputer() {
		return this.computer;
	}

	public void setComputer(Computer computer) {
		this.computer = computer;
	}

	public Date getAssembleDate() {
		return this.assembleDate;
	}

	public void setAssembleDate(Date assembleDate) {
		this.assembleDate = assembleDate;
	}

}
