package com.geezer.adminapp.hibernate;

// Generated Jul 9, 2013 3:22:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer departmentId;
	private String name;
	private String commentary;
	private Set users = new HashSet(0);

	public Department() {
	}

	public Department(String name) {
		this.name = name;
	}

	public Department(String name, String commentary, Set users) {
		this.name = name;
		this.commentary = commentary;
		this.users = users;
	}

	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCommentary() {
		return this.commentary;
	}

	public void setCommentary(String commentary) {
		this.commentary = commentary;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
