package com.geezer.adminapp.hibernate;

// Generated Jul 9, 2013 3:22:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Parttype generated by hbm2java
 */
public class Parttype implements java.io.Serializable {

	private Integer typeId;
	private String name;
	private Set parts = new HashSet(0);

	public Parttype() {
	}

	public Parttype(String name) {
		this.name = name;
	}

	public Parttype(String name, Set parts) {
		this.name = name;
		this.parts = parts;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getParts() {
		return this.parts;
	}

	public void setParts(Set parts) {
		this.parts = parts;
	}

}
