package com.geezer.adminapp.hibernate;

// Generated Jul 9, 2013 3:22:56 PM by Hibernate Tools 4.0.0

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private int partId;
	private Part part;
	private int quantity;

	public Stock() {
	}

	public Stock(Part part, int quantity) {
		this.part = part;
		this.quantity = quantity;
	}

	public int getPartId() {
		return this.partId;
	}

	public void setPartId(int partId) {
		this.partId = partId;
	}

	public Part getPart() {
		return this.part;
	}

	public void setPart(Part part) {
		this.part = part;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
