package com.geezer.adminapp.orm;

// default package
// Generated Jul 18, 2013 12:32:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Computertype generated by hbm2java
 */
public class ComputerType implements java.io.Serializable {

	private Integer typeId;
	private String name;
	private Set computers = new HashSet(0);

	public ComputerType() {
	}

	public ComputerType(String name) {
		this.name = name;
	}

	public ComputerType(String name, Set computers) {
		this.name = name;
		this.computers = computers;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getComputers() {
		return this.computers;
	}

	public void setComputers(Set computers) {
		this.computers = computers;
	}

}
