package com.geezer.adminapp.orm;

// default package
// Generated Jul 18, 2013 12:32:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Computer generated by hbm2java
 */
public class Computer implements java.io.Serializable {

	private Integer computerId;
	private ComputerType computertype;
	private User user;
	private String name;
	private String commentary;
	private Set parts = new HashSet(0);
	private Set assembles = new HashSet(0);

	public Computer() {
	}

	public Computer(ComputerType computertype, User user, String name) {
		this.computertype = computertype;
		this.user = user;
		this.name = name;
	}

	public Computer(ComputerType computertype, User user, String name,
			String commentary, Set parts, Set assembles) {
		this.computertype = computertype;
		this.user = user;
		this.name = name;
		this.commentary = commentary;
		this.parts = parts;
		this.assembles = assembles;
	}

	public Integer getComputerId() {
		return this.computerId;
	}

	public void setComputerId(Integer computerId) {
		this.computerId = computerId;
	}

	public ComputerType getComputertype() {
		return this.computertype;
	}

	public void setComputertype(ComputerType computertype) {
		this.computertype = computertype;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCommentary() {
		return this.commentary;
	}

	public void setCommentary(String commentary) {
		this.commentary = commentary;
	}

	public Set getParts() {
		return this.parts;
	}

	public void setParts(Set parts) {
		this.parts = parts;
	}

	public Set getAssembles() {
		return this.assembles;
	}

	public void setAssembles(Set assembles) {
		this.assembles = assembles;
	}

}
