package com.geezer.adminapp.orm;

// default package
// Generated Jul 18, 2013 12:32:14 PM by Hibernate Tools 3.4.0.CR1

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private int partId;
	private Part part;
	private int quantity;

	public Stock() {
	}

	public Stock(Part part, int quantity) {
		this.part = part;
		this.quantity = quantity;
	}

	public int getPartId() {
		return this.partId;
	}

	public void setPartId(int partId) {
		this.partId = partId;
	}

	public Part getPart() {
		return this.part;
	}

	public void setPart(Part part) {
		this.part = part;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
