package com.geezer.adminapp.orm;

// default package
// Generated Jul 18, 2013 12:32:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private Department department;
	private String aliasname;
	private String lastname;
	private String firstname;
	private String accesskey;
	private String email;
	private String mobile;
	private String phone;
	private Date birthdaydate;
	private Date joindate;
	private String gender;
	private String commentaryl;
	private Set logins = new HashSet(0);
	private Set computers = new HashSet(0);

	public User() {
	}

	public User(Department department, String aliasname, String lastname,
			String firstname, String accesskey, String email, String mobile,
			String phone, Date birthdaydate, Date joindate, String gender) {
		this.department = department;
		this.aliasname = aliasname;
		this.lastname = lastname;
		this.firstname = firstname;
		this.accesskey = accesskey;
		this.email = email;
		this.mobile = mobile;
		this.phone = phone;
		this.birthdaydate = birthdaydate;
		this.joindate = joindate;
		this.gender = gender;
	}

	public User(Department department, String aliasname, String lastname,
			String firstname, String accesskey, String email, String mobile,
			String phone, Date birthdaydate, Date joindate, String gender,
			String commentaryl, Set logins, Set computers) {
		this.department = department;
		this.aliasname = aliasname;
		this.lastname = lastname;
		this.firstname = firstname;
		this.accesskey = accesskey;
		this.email = email;
		this.mobile = mobile;
		this.phone = phone;
		this.birthdaydate = birthdaydate;
		this.joindate = joindate;
		this.gender = gender;
		this.commentaryl = commentaryl;
		this.logins = logins;
		this.computers = computers;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getAliasname() {
		return this.aliasname;
	}

	public void setAliasname(String aliasname) {
		this.aliasname = aliasname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getAccesskey() {
		return this.accesskey;
	}

	public void setAccesskey(String accesskey) {
		this.accesskey = accesskey;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getBirthdaydate() {
		return this.birthdaydate;
	}

	public void setBirthdaydate(Date birthdaydate) {
		this.birthdaydate = birthdaydate;
	}

	public Date getJoindate() {
		return this.joindate;
	}

	public void setJoindate(Date joindate) {
		this.joindate = joindate;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getCommentaryl() {
		return this.commentaryl;
	}

	public void setCommentaryl(String commentaryl) {
		this.commentaryl = commentaryl;
	}

	public Set getLogins() {
		return this.logins;
	}

	public void setLogins(Set logins) {
		this.logins = logins;
	}

	public Set getComputers() {
		return this.computers;
	}

	public void setComputers(Set computers) {
		this.computers = computers;
	}

}
